# Generated by Django 2.2.3 on 2020-12-01 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertownik', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rozmiar',
            new_name='size',
        ),
    ]
