# Generated by Django 2.2.3 on 2020-12-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertownik', '0004_auto_20201201_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
